DROP TABLE IF EXISTS FEE;

CREATE TABLE IF NOT EXISTS FEE (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    from_currency VARCHAR(250) NOT NULL,
    to_currency VARCHAR(250) NOT NULL,
    percent DECIMAL NOT NULL,
    created TIMESTAMP NOT NULL
);

ALTER TABLE FEE ADD CONSTRAINT CURRENCY_UNIQUE UNIQUE (from_currency, to_currency);